---
- name: Hello World Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World
    - name: Print message
      ansible.builtin.debug:
        msg: I am well written
